### ISSUE TITLE
Lag issue with Crystal Growth Chamber

### ISSUE THREAD

**Issue by Neodark7** [bdew/ae2stuff#10]
I think this machine is a "BIT" laggy :D 
![capture](https://cloud.githubusercontent.com/assets/7981869/6180424/00bc323e-b325-11e4-8a78-646cc98f3f7b.PNG)

**Comment by bdew** [comment]
I'm going to assume your locale uses a comma ( , ) as a decimal mark, otherwise it would mean you are running at 0.5 TPS :P

Is there anything special about that crystal growth chamber compared to the other ones that take less time? If it's just loaded with a lot of growing seeds there's not much i can do about it - it does need to go through all it's inventory and update the stacks for them to grow.

**Comment by Neodark7** [comment]
nope they all are empty that's the problem ^^

**Comment by bdew** [comment]
Is it connected to a bigger AE2 network than the other ones?

**Comment by Neodark7** [comment]
nope they all are at the same place

**Comment by Neodark7** [comment]
http://i.imgur.com/7bYrpSp.png
http://i.imgur.com/RWgmn5t.png

**Comment by bdew** [comment]
That's odd. I have no clue why there's such a big difference in timings if they are on the same network and empty.

I have an idea how to improve performance when idle, lets see if it helps.

**Comment by Neodark7** [comment]
okay \o/

**Comment by bdew** [comment]
Try this version http://jenkins.bdew.net/job/ae2stuff-1.7.10/8/artifact/build/libs/ae2stuff-mc1710-0.1.2.8.jar

**Comment by Neodark7** [comment]
Nice ! i test that

**Comment by Neodark7** [comment]
Perfect ! Fixed i thing now i just have this
http://i.imgur.com/UG8dogo.png
http://i.imgur.com/xAysImy.png

**Comment by bdew** [comment]
Yeah this looks more reasonable. Still weird that that one chamber shows up (it's the same one that was taking 50us before that i think?), no idea what's up with that, might be some oddness of the AE2 network or something.

**Comment by Neodark7** [comment]
nope look at the screens ( the block in red ) firstly it was the one at the right and now it's the left one but, fixed it's faar better
