### ISSUE TITLE
Crash when placing any of the AE2 Stuff

### ISSUE THREAD

**Issue by LeChuuck** [bdew/ae2stuff#104]
http://pastebin.com/FPCrjNLU
[crash-2016-06-05_22.13.34-server.txt](https://github.com/bdew/ae2stuff/files/299494/crash-2016-06-05_22.13.34-server.txt)

**Comment by LeChuuck** [comment]
FTB Sky Factory 2.5.0

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
