### ISSUE TITLE
Placeing blocks crushes the game

### ISSUE THREAD

**Issue by sPECIIKOMODO** [bdew/ae2stuff#105]
Every time i place a block from ae stuff the game crushes :(

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/13/16 9:24 AM
Description: Ticking block entity

java.lang.NoClassDefFoundError: appeng/core/WorldSettings
    at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at net.bdew.lib.Event0.trigger(Event.scala:19)
    at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: appeng.core.WorldSettings
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 15 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at net.bdew.lib.Event0.trigger(Event.scala:19)
    at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)

-- Block entity being ticked --
Details:
    Name: ae2stuff.Inscriber // net.bdew.ae2stuff.machines.inscriber.TileInscriber
    Block type: ID #1051 (tile.ae2stuff.Inscriber // net.bdew.ae2stuff.machines.inscriber.BlockInscriber$)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (355,45,76), Chunk: (at 3,2,12 in 22,4; contains blocks 352,0,64 to 367,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #1051 (tile.ae2stuff.Inscriber // net.bdew.ae2stuff.machines.inscriber.BlockInscriber$)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: tECH
    All players: 1 total; [EntityPlayerMP['sPECIIKOMODO'/324, l='tECH', x=354.17, y=45.00, z=78.01]]
    Chunk stats: ServerChunkCache: 514 Drop: 0
    Level seed: 3524722
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (256,64,-16), Chunk: (at 0,4,0 in 16,-1; contains blocks 256,0,-16 to 271,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 1708450 game time, 2401837 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 117353 (now: false), thunder time: 119373 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 415055888 bytes (395 MB) / 1003343872 bytes (956 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 84 mods loaded, 73 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv3-alpha-13} [Applied Energistics 2 Core](minecraft.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) 
    UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120.jar) 
    UCHIJAAAA   OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   IC2{2.2.822-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.822.jar) 
    UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJAAAA   appliedenergistics2{rv3-alpha-13} [Applied Energistics 2](appliedenergistics2-rv3-alpha-13.jar) 
    UCHIJAAAA   bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
    UCHIJAAAA   ae2stuff{0.5.1.61} [AE2 Stuff](ae2stuff-0.5.1.61-mc1.7.10.jar) 
    UCHIJAAAA   Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
    UCHIJAAAA   BattleTowers{1.5.2} [Battle Towers](BattleTowers-1.7.10.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHIJAAAA   BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   CompactMachines{1.7.10-1.21} [Compact Machines](compactmachines-1.7.10-1.21.jar) 
    UCHIJAAAA   BrandonsCore{1.0.0.12} [Brandon's Core](BrandonsCore-1.0.0.12.jar) 
    UCHIJAAAA   DraconicEvolution{1.0.2e} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2e.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.35_beta} [EnderCore](EnderCore-1.7.10-0.2.0.35_beta.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.3.0.425_beta} [Ender IO](EnderIO-1.7.10-2.3.0.425_beta.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.38} [EnderStorage](EnderStorage-1.7.10-1.4.7.38.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.347} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.347.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAA   GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   Mekanism{9.0.2} [Mekanism](Mekanism-1.7.10-9.0.2.273.jar) 
    UCHIJAAAA   MekanismGenerators{9.0.2} [MekanismGenerators](MekanismGenerators-1.7.10-9.0.2.273.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJAAAA   OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCHIJAAAA   JotatosPracticalities{0.6.2} [Practicalities](practicalities-1.7.10-0.6.2.jar) 
    UCHIJAAAA   quantumflux{1.7.10-1.3.4} [QuantumFlux](QuantumFlux-1.7.10-1.3.4.jar) 
    UCHIJAAAA   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHIJAAAA   rftools{4.23} [RFTools](rftools-4.23.jar) 
    UCHIJAAAA   SolarExpansion{1.6a} [Solar Expansion](SolarExpansion-Basic-1.6a.jar) 
    UCHIJAAAA   SolarFlux{1.7.10-0.8b} [Solar Flux](SolarFlux-1.7.10-0.8b.jar) 
    UCHIJAAAA   SSR{Alpha 0.9a} [Soul Shards: Reborn](Soul-Shards-Reborn-Mod-1.7.10.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.347} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.347.jar) 
    UCHIJAAAA   McMultipart{1.2.0.347} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.347.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: alpha rv3-alpha-13 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.4-114
    ThermalExpansion: -[1.7.10]4.1.2-240
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.2.0-171
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from appliedenergistics2-rv3-alpha-13.jar
        \* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.4-114.jar
        \* BuildCraftAPI|core (1.0) from SolarExpansion-Basic-1.6a.jar
        \* BuildCraftAPI|tools (1.0) from SolarExpansion-Basic-1.6a.jar
        \* CoFHAPI (1.7.10R1.0.2) from RandomThings-2.2.4.jar
        \* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|core (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
        \* CoFHAPI|energy (1.7.10R1.0.13) from ImmersiveEngineering-0.7.7.jar
        \* CoFHAPI|fluid (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHAPI|inventory (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHAPI|item (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.425_beta.jar
        \* CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|gui|element (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|gui|slot (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|render (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|util (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
        \* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
        \* DraconicEvolution|API (1.2) from Draconic-Evolution-1.7.10-1.0.2e.jar
        \* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
        \* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
        \* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
        \* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.425_beta.jar
        \* IC2API (1.0) from industrialcraft-2-2.2.822.jar
        \* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.7.7.jar
        \* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
        \* MekanismAPI|core (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|energy (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|gas (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|infuse (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|laser (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|reactor (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|recipe (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|transmitter (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* MekanismAPI|util (9.0.0) from Mekanism-1.7.10-9.0.2.273.jar
        \* OpenBlocks|API (1.1) from OpenBlocks-1.7.10-1.5.1.jar
        \* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.7.7.jar
        \* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
    EnderIO: Found the following problem(s) with your installation:
                  \* The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from ImmersiveEngineering-0.7.7.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['sPECIIKOMODO'/324, l='tECH', x=354.17, y=45.00, z=78.01]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

**Comment by NaokiSato102** [comment]
Sorry, I don't know which one to choose. Where can I find the tags?

**Comment by Myratec** [comment]
There are 2 Types of files. One with rv3 in the name and without. Look wich version of AE2 is installed and use the right type of the mod.
