### ISSUE TITLE
import bus on Advanced Inscriber stops Inscriber from receiving power

### ISSUE THREAD

**Issue by scherre** [bdew/ae2stuff#106]
I am not sure if this is a problem with AE2 Stuff or with AE itself.. but as the title states, my Advanced Inscribers do not receive power from the network if there is an ME Import Bus on the cable that connects them to the network. If I remove the Import Bus, the Inscriber fills with power really quickly.. but of course the stuff just sits there :eyes: 

I am using the Agrarian Skies 2 pack. I am not sure if you need any other information, I obviously don't have any crash reports or anything like that.

**Comment by bsaksida** [comment]
This is how AE works. Any AE machines gets power from network, as long as it is connected to cable or having placed next to other AE machines. AE Machines will not get powered through any import/export buses, in same cases even interface can not transfer power (If configured,the side with arrow that it points will not suplly power or interface that does not take full block).

In your setup, you will have to connect to cable on other side put import bus.
Advanced and non Advance inscribers do not take any chanels. If you are worried, you can put queartz fiber, to transfer power, but not data (Channels)

**Comment by bdew** [comment]
As @bsaksida said - that's how AE2 network works. Busses don't provide power to the block they are attached to.

**Comment by scherre** [comment]
Thanks for responding so quickly. I had put an extra piece of cable to solve the power problem, which is a bit annoying since it's less pretty but oh well!
