### ISSUE TITLE
[Bug] Advanced inscriber not receiving power through quartz fiber

### ISSUE THREAD

**Issue by Meryl** [bdew/ae2stuff#108]
Hello,

I'm using 0.5.1.9 (the rv3 alpha) on the FTB Infinity Evolved modpack (set to _normal mode_), but I've run into an issue trying to power the advanced inscriber.

Seeing as how a picture is worth a thousand words, [this](https://i.imgur.com/EOrwLVL.png) is an image of my setup. What it's supposed to do, is send power from the 'main' network's blue cables, through the quartz fiber and then into the advanced inscriber via the red glass cable. As you should be able to see, that isn't happening (and for the record, the inscriber is filled with a calculation press and pure certus quartz): The inscriber is sleeping, and has no power.

If I remove the red wire and the quartz fiber and connect the inscriber to the network through a blue cable, the inscriber starts receiving power and works as intended.

**Comment by bdew** [comment]
I'll look into it when i get the chance... but that setup is pretty pointless. Since it doesn't use channels you can just have it on your main network.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
