### ISSUE TITLE
Crash when right clicking on wireless connector with wireless setup kit 

### ISSUE THREAD

**Issue by jonharn** [bdew/ae2stuff#110]
[crash-2016-08-22_09.44.47-server.txt](https://github.com/bdew/ae2stuff/files/430289/crash-2016-08-22_09.44.47-server.txt)
Right clicked on wireless connector with wireless set up kit and game crashed

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

**Comment by jonharn** [comment]
[crash-2016-08-22_10.27.24-client.txt](https://github.com/bdew/ae2stuff/files/430370/crash-2016-08-22_10.27.24-client.txt)
I added the file and it crashed again before i even launched
