### ISSUE TITLE
Updated ae2stuff file to version suggested and game crashed 

### ISSUE THREAD

**Issue by jonharn** [bdew/ae2stuff#112]
[crash-2016-08-22_10.27.24-client.txt](https://github.com/bdew/ae2stuff/files/430372/crash-2016-08-22_10.27.24-client.txt)
#110

**Comment by bdew** [comment]
Use the download button at the top of the page, not under "Additional Files"...

You need to get ae2stuff-rv3-0.5.1.9-mc1.7.10.jar

Not ae2stuff-rv3-0.5.1.9-mc1.7.10-dev.jar - this is for other developers and will not work in normal minecraft.
