### ISSUE TITLE
[Bug] Placing Crystal Growth Chamber crashes game

### ISSUE THREAD

**Issue by JFMillerUSA** [bdew/ae2stuff#113]
ae2stuff-0.5.1.61
appliedenergistics2-rv3-beta-6
Forge 10.13.4.1614

[Crash Report](http://pastebin.com/raw/A4tzShMp)

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
