### ISSUE TITLE
Game Crashes after placing advanced Incriber

### ISSUE THREAD

**Issue by hiFloh** [bdew/ae2stuff#114]
after this crash I'm not able to enter the world again.
Crashreport: [crash-2016-09-13_14.58.27-server.txt](https://github.com/bdew/ae2stuff/files/469858/crash-2016-09-13_14.58.27-server.txt)

**Comment by bsaksida** [comment]
You are using wrong version ae2stuff. Crashlog says you have regular ae2stuff mod, but applied energistics is rv3. Install ae2stuff rv3 version

**Comment by hiFloh** [comment]
That's right I used a non rv3 version.
I tried it with the right version and it worked fine.
Thanks for help.
