### ISSUE TITLE
Can't Place Inscriber Name Press in Advanced Inscriber

### ISSUE THREAD

**Issue by Hazmatik** [bdew/ae2stuff#115]
The inscriber name presses are really handy for renaming things without having to use XP. Would be nice if the Advanced Inscriber supported this function.

AE2 Version: rv3-beta-6
AE2 Stuff Version: rv3-0.5.1.9

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
