### ISSUE TITLE
[Bug] Too many wireless conectors and advanced inscribers.

### ISSUE THREAD

**Issue by waterphoenix314** [bdew/ae2stuff#116]
I have a small ME network with 6 wireless connectors and 4 advanced inscribers. I first noticed when I installed Player API for Galacticraft and Extra Utilities portal compatibility. After removing Player API from the server the number of Wireless Connectors went for about 50 to about 16. Then I removed Player API from my client, this fixed the Wireless Connectors but I saw 12 Advanced Inscribers. Simply replacing the Advanced Inscribers fixed them.

This caused a major power drain that stopped everything from working. I tried to replicate the bug by reinstalling Player API and got 6 Wireless Connectors and 7 Advanced Inscribers. It seams like when I leave the area and come back the numbers change. I used the network tool to get all these numbers.

I'm using lots of different mods, so I've included a list of all the jars.
[Mods.txt](https://github.com/bdew/ae2stuff/files/505304/Mods.txt)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
