### ISSUE TITLE
Safe to use current ae2stuff with the new AE2 beta?

### ISSUE THREAD

**Issue by jpeaglesandkatz** [bdew/ae2stuff#122]
I see there is a new AE2 beta out. I'm reluctant to update to it on my client/server since the last update caused AE2stuff to behave somewhat irratic. 

Thanks! :)

**Comment by bdew** [comment]
I've just pushed a build made with alpha 8 (there is no beta for 1.10 yet AFAIK). I don't know of any specific issues from my cursory testing, but if you run into any please report them.

Also the bug tracker isn't really an appropriate place for questions like that.
