### ISSUE TITLE
Seeds do not grow in the chamber

### ISSUE THREAD

**Issue by chezpaul** [bdew/ae2stuff#124]
I'm running ae2stuff-0.5.1.61-mc1.7.10 with AE2 rev3 beta 6 & bdlib-1.9.4.109-mc1.7.10
Running on a Thermos 1614.58 Server.
The first time I placed the chamber down, the server crashed.
I relaunched it and the chamber was there. I was able to automated it out. Started crafting Pure crystals and send 64 seeds to be grown. The first 2 seeds stopped at 16%, the next 2 at 11% and so on until 52 left at 0%.
Whatever I put in there manually ,nothing grows either.
There is no crash log when this happens, but here is the initial server log with the crash log at the end of it.
[http://pastebin.com/0YEW3MEw](http://pastebin.com/0YEW3MEw)

Thanks

**Comment by bdew** [comment]
If you are using AE2 rv3 beta you need to use builds of AE2Stuff tagged with "-rv3", the last one is here: https://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

That's what caused the initial crash and probably left everything in an inconsistent state. After updating break and replace the growth chamber and see if it fixes the issue.

**Comment by chezpaul** [comment]
Thanks.. I did indeed read your red line about the -rv3 but I could find any links to rv3 on the curse page. Thanks for pointing it out.
