### ISSUE TITLE
Inscriber won't pull out press or duplicates when slot is unlocked [1.10.2/0.6.0.7]

### ISSUE THREAD

**Issue by tgstyle** [bdew/ae2stuff#126]
I tried using EnderIO Conduit and Steve's Factory Manager Reborn to remove the press from an unlocked slot, neither worked. SFMR pulled it and duped it, as it actually never left the slot, but still ended up in a chest over and over again.

**Comment by tgstyle** [comment]
Seems like the item dupe is internal to SFMR, however you still cannot remove the presses with automation.
https://github.com/gigabit101/StevesFactoryManager/issues/25

**Comment by JoeMylinn** [comment]
Having a similar problem, when trying to use the inscriber to automatically craft processors, using the AE2 autocraft system, a lot of times the presses won't get extracted, failing the auto craft process, but only when having one or more speed upgrades installed, and sometimes it does work (couldn't determine what affects it yet,  gonna do more testing).

**Comment by md5i** [comment]
I am having the same problem.  The presses aren't always extracted by the import bus attached, even though both slots are unlocked.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by artheus** [comment]
This issue is relevant to me, playing the modpack Beyond from FeedTheBeast. Minecraft version 1.10.2

**Comment by artheus** [comment]
Only way I get this working is putting a Hopper under the Inscriber
