### ISSUE TITLE
[Request] Powered grindstone

### ISSUE THREAD

**Issue by xenoflot** [bdew/ae2stuff#127]
Hi,

Our server pack doesn't have the usual array of mods. We have AE2 (1.10) but no tech mods that provide a grinder that will turn certus and fluix crystals into dust. It seems at this stage that CraftTweaker doesn't support the tech mods we do have. I figured a powered AE2 grindstone would be right up the alley of AE2Stuff!

Cheers!

**Comment by Ravin890** [comment]
Ae2 has its own recipe files in the configs area unless that was changed

**Comment by Ravin890** [comment]
And i just finally realized this was for ae2stuff not ae, ignore my msgs...

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
