### ISSUE TITLE
Want to adjust power consumtion

### ISSUE THREAD

**Issue by idnthvn** [bdew/ae2stuff#128]
For the wireless connectors, id like to chance the power consumption.
I see that there is no config but a place for overide configs. 
ive googled and searched and have had no luck. 
could someone please let me know??? thank you

**Comment by SDUBZ** [comment]
@idnthvn mentioned here https://github.com/bdew/ae2stuff/issues/143

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
