### ISSUE TITLE
[Feature Request] Pattern Encoder uses Pure Quartz over Quartz

### ISSUE THREAD

**Issue by Xiaminou** [bdew/ae2stuff#130]
When encoding patterns with the Pattern Encoder it should use Pure Certus/Nether Quartz and Pure Fluix Crystals instead of common ones like the Pattern Terminal does.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
