### ISSUE TITLE
Adv inscribers delete power

### ISSUE THREAD

**Issue by TheUnderTaker11** [bdew/ae2stuff#133]
When hooked up to enderIO cables(Not tested with others) The advanced inscriber will accept and just delete however much the cable can transfer.
MC 1.10.2, ae2stuff version 0.6.0.9

**Comment by bdew** [comment]
Err, they aren't supposed to accept external and i don't implement any energy system stuff except AE2 energy... I'll look into it but it's very likely something else is eating your power.

**Comment by TheUnderTaker11** [comment]
I know 100% it is the advanced inscribers, I didn't mention it but I spawned in a full vibrant capacitor and wired it only to the inscriber, and it destroyed all the power inside of it.

**Comment by CasperHalleriet** [comment]
It seems like everything that is hooked up to a rf source is eating the rf. I had the Crystal growth chamber hooked up to rf and it completely drained it (even when the chamber was in idle) . I tried putting down a Creative Capacitor bank from Ender io next to it, and it used the 500000rf that could be extracted from it. After that i tried it with the inscribers, and they seem to have the same behaviour. 

When i connected both the inscribers en the chamber to an ae2 network it stopped draining energy when the machine was idling, and it used a more reasonable amount of power when doing work.

**Comment by shaggy1395** [comment]
Throwing in my confirmation as well.  The advanced inscribers and crystal growth chamber both eat as much power as you can feed them.  If I apply a redstone signal to the growth chamber to disable it, it will then stop sucking power.

Tested on AE2 power only per bdew's mention, there appears to be no heavy drain on the power.

Currently running All The Mods pack for 1.10.2
- ae2stuff-0.6.0.9-mc1.10.2.jar
- appliedenergistics2-rv4-alpha-11.jar

**Comment by ouroborus** [comment]
I'm seeing the same issue where the Advanced Inscriber guzzles power from enderio.

(I was originally using the AE2 Inscribers and those seemed to be playing nicely with enderio power.)

Edit: Seems like it's all the ae2stuff machines.

Any chance of getting ae2stuff to accept power the same way ae2 does?

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
