### ISSUE TITLE
Can't Combine Genetic Templet with Gene Sample

### ISSUE THREAD

**Issue by ambycloud** [bdew/ae2stuff#134]
This is the second time this has happen.  It only affect the specific safe file I'm playing.  I have made 20 or so completed Genetic Templets with all 13 various samples.  Then for no apparent reason I can no longer combine the Genetic Templet and a new Gene Sample on the crafting table.  It doesn't matter if I try to craft just one or up to 9.  It just wont give me an output item with a Genetic templet with the gene sample attributes.  Nothing shows up in the output.  Similar to the way banned items work on multiplayer servers.  But this is a single player game and no items are banned.  I double checked the banned items cfg to be sure.  Nothing there.

I loaded up another single player game and I can build them there with no problem.

I even loaded up a backup of the game Im having the problem with from yesterday when I KNOW it worked and I still can't build them.

I recreated my game by making a new game with the same seed.  Then from my glitched game I copied over only the "region" data to the new game which includes all data on buildings and map stuff but no character data.  It still will NOT work and I can't combine a genetic template with a gene sample.

I am playing the Tekkit Legends Mod pack.  I tried updating to the newest version of gendustry but then I got an error loading saying I needed a newer version of forestry,  so i got that, then I tried loading it and got an error saying I needed a newer version of forge.  So i got that and then I was stuck.  It keeps saying I need a newer version of forge though as far as I know I have it and its installed correctly. (but maybe not).

The point is I can't build templates.  would rather not start over as it will just happen again.  Can't figure out, assuming its even possible, how to update the mods to a newer version or even if that would fix the problem.

I'm in desperate need of help.

**Comment by bdew** [comment]
Does anything show up in the logs when you do this?

Also can you try making a fresh template (with nothing in it) and combining the sample with it? Does that work?

**Comment by ambycloud** [comment]
dont know how to check logs.  did try fresh everything and still wouldn't work.  Again it only affects this one game.  Not my other saved games.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
