### ISSUE TITLE
ae2 stuff breaks itself

### ISSUE THREAD

**Issue by InflamedSebi** [bdew/ae2stuff#135]
i placed my growth chambers & inscribers, went away for some time, as soon as i returned all the growth chambers & inscribers were dropped on the ground and their contends vanished. Happens everytime.

Pack FTB Beyond v 1.5.1

**Comment by InflamedSebi** [comment]
seems like server restart fixed it. But happened again after a while ...

**Comment by bdew** [comment]
Looks like the same bug as #131. I'm looking into it, but haven't managed to figure out why it's happening yet. Please follow that bug for more info.
