### ISSUE TITLE
Wireless Connectors randomly just dropping on floor 

### ISSUE THREAD

**Issue by ghost** [bdew/ae2stuff#136]
So since Beyond updated to 1.5.3 Wireless Connectors in certain chunks are dropped(like broken) on chunk load.  It happens only in certain chunks and every time the chunk is loaded.  After I replace it, it has no issue until the chunk is unloaded then reloaded and it happens again, everytime.

**Comment by ghost** [comment]
The exact same ones are broken.  I have 10 chunks, and about 40 wireless connectors.  Only Connectors in 2 of those chunks break and all Connectors in those 2 chunks break.  Happens every time.

**Comment by ghost** [comment]
Also, it only happens if the Wireless Connectors are connected

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
