### ISSUE TITLE
Issue/Feature Request - Crystal Growth Chamber has no output slots

### ISSUE THREAD

**Issue by xBlizzDevious** [bdew/ae2stuff#137]
The title suggests the feature I want. The issue is that I have auto-crafting set up but I can't auto-craft more than 27 stacks at once because it fills the inventory up leaving no slots for output.

Perhaps a few output slots could be added so that you can always craft things, even if the inventory is full?

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
