### ISSUE TITLE
Issue things disapear

### ISSUE THREAD

**Issue by jeromecoder** [bdew/ae2stuff#138]
Hello,
I have advanced Inscribers. I use them with ME import/export bus. But when the chunks where they are unload all stuff disapear ! Even the patterns in the Me interface connected to these inscribers.

**Comment by Kris1432** [comment]
having this issue also ^

**Comment by ResqDiver1317** [comment]
Yea, we are having the disappearing issue on our FTB Beyond pack. So far I have had players report to me that advanced inscribers and Crystal Growth Chambers disappear. We are running the FTB Beyond (version 1.10 beta) on our server with SpongeForge. It's hard to reproduce and seems random, but it is consistent enough to be an issue.

**Comment by camaro2010** [comment]
Same here, inscribers and growth chambers disappearing. We are also running FTB Beyond 1.10 beta. but without SpongeForge.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by ResqDiver1317** [comment]
So is this issue not getting fixed for 1.10.2? Good to know for everyone running 1.10.2 packs on their servers...
