### ISSUE TITLE
Not creating config file

### ISSUE THREAD

**Issue by PsLanger** [bdew/ae2stuff#140]
Hi,
i'm using Applied Energistics RV3 beta 6 together with AE2 Stuff RV3 0.5.1.9 and want do change the RF consumption of wireless connector, but AE2 Stuff doesn't create a config file to change the values.
Ist it possible to create a own file? If yes how must it be named and what should be inside?

Tanhks for help

**Comment by SDUBZ** [comment]
@PsLanger mentioned here https://github.com/bdew/ae2stuff/issues/143

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
