### ISSUE TITLE
Incompatibility with newer versions

### ISSUE THREAD

**Issue by MPeti1** [bdew/ae2stuff#141]
Hi!
I needed to update ae2 to the latest rv3 (beta) release, because in the latest "stable" release i had major issues. And, when i wanted to load my save, the game crashed with [this log](https://gist.github.com/MPeti1/b93841f781dcfd65eea710b98cab33f9).
It seems AE2 Stuff has some incompatibility issues with the inscriber.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
