### ISSUE TITLE
AE2 stuff - Wireless Receiver doesn't have a config

### ISSUE THREAD

**Issue by ThisNThat01** [bdew/ae2stuff#143]
i've been trying to change the values for the wireless receivers but i can't find anything on them. i tried looking around to try to find how to do it but can't find anything. the amount of power the wireless receivers use is insane so i wanted to change it

**Comment by R1ZL4** [comment]
If you mean the wireless connectors (wireless receivers are not in AE2Stuff)

Create a file in config/AE2Stuff called config.cfg and add:

```
cfg Machines {
    cfg Wireless {
        PowerBase = 10
        PowerDistanceMultiplier = 1
    }
}
```

The formula is Power use = PowerBase + PowerDistanceMultiplier * Distance^2 (AE/t)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by Xevion** [comment]
This is still present in 1.12.2. No 'config file' is generated at all.
```
├───AE2Stuff
│   │   readme.txt
│   │
│   └───overrides
```

---
**General Versions**
`minecraft 1.12.2`
`StoneBlock-1.0.31`

**Mod Versions**
`forge-1.12.2-14.23.5.2768-universal`
`ae2stuff-0.7.0.4-mc1.12.2`
`appliedenergistics2-rv6-stable-4`
