### ISSUE TITLE
Advanced Inscriber crashes server, makes it impossible to relaunch

### ISSUE THREAD

**Issue by walale12** [bdew/ae2stuff#145]
Hi, my server crashes and becomes impossible to relaunch when an advanced inscriber is placed. Here is the crashlog.
[crash-2017-07-02_17.27.09-server.txt](https://github.com/bdew/ae2stuff/files/1117922/crash-2017-07-02_17.27.09-server.txt)

**Comment by Ommina** [comment]
You appear to be using ae2stuff-0.5.0.56 (Requirements: Applied Energistics 2 rv2.stable) with AE2 rv3 beta.

**Comment by GBconnorbee** [comment]
@Ommina  Hello there so I think I'm having the same problem but i was not sure what versions i need of the mods you were talking about, I'm in minecraft version 1.7.10 its my own privet pack and i have  ae2stuff-0.5.0.56 with ExtraCells 2.3.13b197 (not sure if they are the right versions) so would i need AE2 rv3 beta or ae2 rv2.stable ?

**Comment by Ommina** [comment]
@GBconnorbee Were it to be me, I would use AE2 rv3 beta-6, ae2stuff-rv3-0.5.1.9-mc1.7.10, and ExtraCells-1.7.10-2.3.14b197

If you want to stay with ae2stuff-0.5.0.56, then you'll have to use ae2 rv2.

**Comment by PaulLeichtfried** [comment]
Same issue here, I use AE2 rv3 beta 6 together with ae2stuff-rv3-0.5.1.9-mc1.7.10 but the server is still crashing after I place an advanced inscriber.
When i try to download ae2stuff-rv3-0.5.1.9-mc1.7.10 i immediately get the older ae2stuff-0.5.0.56-mc1.7.10, at least the file name is the old one.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
