### ISSUE TITLE
AE2Stuff and SpongeForge

### ISSUE THREAD

**Issue by Master-Jynx** [bdew/ae2stuff#146]
Im playing on a small SpongeForge smp server using MC 1.10.2 and forge 2297
and ae2stuff-0.6.0.9-mc1.10.2 with AE2 rev4 alpha 11 and several other mods.

The machine used are the Adv. Inscriber, Growth Chamber, Pattern Encoder.
When placed and powered, individually, in combination or in any pair combo,
sponge is unable to unload the chunk(s) they are in and the console is spammed 
nonstop with various errors until someone returns to the base causing the region to load.
As long as someone in nearby, no error message are generated.
The Adv. Inscriber and Pattern Encoder generate this sample of errors : https://pastebin.com/SsqVBk2q
The Growth Chamber causes these errors : https://pastebin.com/SymYVmSC

The chunk loading can be seen when the blocks are used and the player uses 2 enderchests from the enderchest mod to mine in a different dimension and the endrchest is emptied by automation at his base faster then he can fill it

**Comment by bdew** [comment]
Looks to me like a general issue with AE2, the first log you posted doesn't even mention any of my code in the trace. Sadly the last update to AE2 was over half a year ago an it's pretty much dead :\

**Comment by Master-Jynx** [comment]
WE noticed that oddity , too.
only when a growth chamber is in use, do the errors refer to you mod.
None of the errors occur if when no AE2Stuff machines are used or when a player is present
and the entire region is loaded.

**Comment by fusionmc-evilscoop** [comment]
*removed*

**Comment by Master-Jynx** [comment]
How is SpongeBootstrap , a mod released to deal with coremod load order issues,at start up, supposed to help with, what is probably an AE2 controller blocking a chunk unload attempt after startup, during gameplay?

**Comment by fusionmc-evilscoop** [comment]
wrong thread....my bad
was a browser cock up weeks ago

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
