### ISSUE TITLE
wireless connectors in other chunks disconnecting

### ISSUE THREAD

**Issue by acidjazz** [bdew/ae2stuff#147]
This happens in FTB Beyond and allthemods 2, every time I log back on i have to re-connect each wireless connector with my wireless setup kit.  All wireless connectors w/in the chunk of the me controller are always fine.

**Comment by Kyub3y** [comment]
I'm having the same issue in a FTB beyond server, have to reconnect them every time the server reset

**Comment by acidjazz** [comment]
@bdew any idea? and now that ae2 is in 1.12 any ETA? :)

**Comment by bdew** [comment]
I've been focusing on my other mods updates and stabilizing for 1.12 but i'll look into this soon (tm).

**Comment by Nidaelie** [comment]
Have the same problem on this 1.10 version in atm expert modpack, any eta or clue about it??

**Comment by Bendder** [comment]
Happening in Project Ozone Lite (1.10.2).

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by acidjazz** [comment]
@bdew did you fix this? this a pretty huge annoying  issue

**Comment by Ravalli03** [comment]
I take it no chance of this being fixed for 1.10? Really hope you can.

**Comment by yazzledore** [comment]
It's happening to me in Enigmatica2:Expert, so still relevant in 1.12.

**Comment by Panzer1119** [comment]
Still not fixed? I'm using "AE2Stuff 0.7.0.4 (MC 1.12.2)" and after a Server restart all Wireless Connectors had to be reconnected...

Edit: After i chunkloaded them they worked properly.
