### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by hottheadliberty** [bdew/ae2stuff#15]
not sure where you want these
any help on it would be great

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 3/25/15 11:04 AM
Description: Ticking block entity

java.lang.AbstractMethodError
	at appeng.me.GridNode.FindConnections(GridNode.java:236)
	at appeng.me.GridNode.updateState(GridNode.java:147)
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:35)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.me.GridNode.FindConnections(GridNode.java:236)
	at appeng.me.GridNode.updateState(GridNode.java:147)
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:35)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)

-- Block entity being ticked --
Details:
	Name: ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.TileGrower
	Block type: ID #425 (tile.ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.BlockGrower$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (110,71,220), Chunk: (at 14,4,12 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #425 (tile.ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.BlockGrower$)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Devin's World
	All players: 1 total; [EntityPlayerMP['hottheadliberty'/366, l='Devin's World', x=110.40, y=71.00, z=217.78]]
	Chunk stats: ServerChunkCache: 685 Drop: 0
	Level seed: -380717751769695906
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (84,64,232), Chunk: (at 4,4,8 in 5,14; contains blocks 80,0,224 to 95,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10940 game time, 10940 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 142052 (now: false), thunder time: 9807 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 630312408 bytes (601 MB) / 1005060096 bytes (958 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 19 mods loaded, 19 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bdlib{1.6.5.52} [BD Lib] (bdlib-mc1710-1.6.5.52.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ae2stuff{0.1.6.14} [AE2 Stuff] (ae2stuff-mc1710-0.1.6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.3.7} [BuildCraft] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.3.7} [BC Transport] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.7} [BC Silicon] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.3.7} [BC Builders] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.3.7} [BC Energy] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.3.7} [BC Factory] (buildcraft-6.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	advgenerators{0.9.11.hotfix1} [Advanced Generators] (generators-mc1710-0.9.11.hotfix1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	CoFHCore: -[1.7.10]3.0.0RC7-211
	List of loaded APIs: 
		* appliedenergistics2|API (rv1) from appliedenergistics2-rv1-stable-1.jar
		* BuildCraftAPI|blueprints (1.1) from buildcraft-6.3.7.jar
		* BuildCraftAPI|boards (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|core (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|events (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|facades (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|filler (2.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|gates (4.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|power (1.3) from buildcraft-6.3.7.jar
		* BuildCraftAPI|recipes (2.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|robots (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|statements (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|tiles (1.1) from buildcraft-6.3.7.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-6.3.7.jar
		* BuildCraftAPI|transport (3.0) from buildcraft-6.3.7.jar
		* CoFHAPI (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|block (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|core (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-6.3.7.jar
		* CoFHAPI|fluid (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|inventory (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|item (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|tileentity (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|transport (1.7.10R1.0.10) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHAPI|world (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|audio (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|gui (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|gui|container (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|gui|element (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|gui|slot (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|inventory (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|render (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|render|particle (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|util (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|util|helpers (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|util|position (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
		* CoFHLib|world (1.7.10R1.0.0RC7) from CoFHCore-[1.7.10]3.0.0RC7-211.jar
		* CoFHLib|world|feature (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC7-127.jar
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['hottheadliberty'/366, l='Devin's World', x=110.40, y=71.00, z=217.78]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by bdew** [comment]
That version of AE2 Stuff only works with AE2 rv2-beta.
If you want to use rv1 - get this version http://minecraft.curseforge.com/mc-mods/225194-ae2-stuff/files/2217706
