### ISSUE TITLE
[1.12.1] Bug AE2 Growth Crystal Chamber makes crafting units break when placed next to it

### ISSUE THREAD

**Issue by erwin1234777** [bdew/ae2stuff#153]
Funny story, had a normal 10x 64k crafting cpu's ontop of the ae2 growth crystal chamber. nothing wrong (placed the crafting units before the chamber), untill me and my friend requested 900 64k drives to fill our drive storage bay. well, turns out if you unload the chunk or stop rendering it(in anotehr dimension for example), when you come back the breaking crafting unit nearby happens. well, lets just say 11400 entities are now on the floor :)

**Comment by bdew** [comment]
Can't reproduce this.

Can you try with the latest version (0.7.0.2) and alpha 8 and see if it still happens?

If it does please provide more info about your setup.
