### ISSUE TITLE
[1.12.2] Unable to remove recipe with CraftTweaker

### ISSUE THREAD

**Issue by NielsPilgaard** [bdew/ae2stuff#156]
Hey!

I'm trying to remove the recipe for the Crystal Growth Chamber to add my own, but I'm unable to remove it. The new recipe works fine.
Should I report this to CraftTweaker aswell? I'm fairly certain it's not on their end.

Minecraft 1.12.2
Forge 1.12.2 - 14.23.0.2512
ae2stuff-0.7.0.3-mc1.12.2

**Comment by bdew** [comment]
I'm not very familiar with CraftTweaker, i don't think i'm doing anything special they can't handle.

You can also use my own config to change recipes - look here for example - https://github.com/bdew/ae2stuff/blob/mc1.12/resources/assets/ae2stuff/config/recipes.cfg

**Comment by NielsPilgaard** [comment]
I believe removals with CraftTweaker will fail, if the recipe is loaded during postInit, is that the case?

Thanks for the config option, I'll try, but it looks a bit confusing :p

**Comment by bdew** [comment]
Yes it's in postInit at the moment... i can actually move it up to init if that helps anything. I'll change it in the next build.

**Comment by NielsPilgaard** [comment]
Damn that was fast, thank you! Removing the recipe with CraftTweaker now works :D
