### ISSUE TITLE
1.12.2 - Wireless Setup Kit/Wireless Connector interactions broken

### ISSUE THREAD

**Issue by valeriantech** [bdew/ae2stuff#158]
[latest.log](https://github.com/bdew/ae2stuff/files/1385552/latest.log)

Tried with a clean profile, only ae2stuff, bdlib, and AE2 with latest alpha forge (2512), getting Error executing task caused by the ItemWirelessKit when right clicking a Wireless Connector with the Wireless Setup Kit.

The error goes to the log, user gets no feedback, and this does not cause a crash.

**Comment by bdew** [comment]
Might be an api change in beta 1, i haven't looked at it yet.

**Comment by bdew** [comment]
Yep, will be fixed with next update.
