### ISSUE TITLE
not able to craft ae2stuff

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [bdew/ae2stuff#159]
im not able to craft all the ae2stuff, also it doesnt work to give it to me with cheat mode on.
icons are shown in the list.
![grafik](https://user-images.githubusercontent.com/4589916/31862559-5ce9c894-b72f-11e7-8081-4e879a4daf61.png)
there is a tooltip error, but i dont know if thats ae2stuff or jei

Used versions:
Forge: 1.12.2-14.23.0.2512
appliedenergistics2: rv5-beta-1
bdlib: 1.14.3.10
ae2stuff: 0.7.0.4

**Comment by bdew** [comment]
Post logs please.

**Comment by 5t0rmr1d3r** [comment]
i've not filtered it out.
[fml-client-latest.log](https://github.com/bdew/ae2stuff/files/1405221/fml-client-latest.log)

**Comment by bdew** [comment]
Did you try to actually craft any of the items? 

It looks from the log that the recipes are registered correctly... so it might just be  a JEI issue.

The tooltip error doesn't make too much sense to me either.

**Comment by 5t0rmr1d3r** [comment]
![grafik](https://user-images.githubusercontent.com/4589916/31889662-263599d8-b7f0-11e7-8f1b-f311c7167bec.png)
it doesnt work either in crafting terminal nor in normal crafting table

**Comment by bdew** [comment]
Hm weird... i've tried and can't reproduce neither of the issues with latest versions of JEI/AE2/AE2Stuff.

Might be some third party (core)mod doing something weird...

Can you try to install only JEI, AE2 and AE2Stuff and see if it still happens? If it doesn't try adding the rest of your mods and see which one breaks it.

**Comment by 5t0rmr1d3r** [comment]
i could solve it!
When i play with the same client installation a local game, it worked.
That took me to look at our serverinstallation.
It seems one of our serveradmins deleteted ae2stuff by accident...

**Comment by bdew** [comment]
Heh, interesting that caused so much weirdness, but good you found your problem :)
