### ISSUE TITLE
Advanced Inscriber crashes MC

### ISSUE THREAD

**Issue by modsareawesome** [bdew/ae2stuff#164]
well, another issue. the advanced inscriber crashes the game while loading the world.

The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;

**Comment by bdew** [comment]
Please don't open multiple issues about the same thing. The error is likely because you are using mismatched versions of AE2 and AE2Stuff. What versions of both mods are you running?
