### ISSUE TITLE
Advanced inscriber unable to craft circuits with one single press of each type

### ISSUE THREAD

**Issue by diegofpais** [bdew/ae2stuff#165]
When trying to craft x number of a circuit, x number of presses are required. (AE stuffs 0704, AE2 rv5-stable-3, Modern Skyblock 2  2722)

**Comment by bdew** [comment]
That's just how AE crafting works, if you put the press in the recipe. You can make sparate inscribers for each process and keep the relevant press inside all the time - then you don't need to specify it in the recipe.

**Comment by diegofpais** [comment]
Thank you for answering. I got you, but in that way you still need five inscribers as in vanilla ae2, which in my opinion defeats, a great deal of, the purpose of the advanced block.
