### ISSUE TITLE
Chat message about InGame Wiki

### ISSUE THREAD

**Issue by OrdinatorStouff** [bdew/ae2stuff#167]
There's a chat message when joining world mentioning that AE2Stuff uses InGameWiki and suggests that it be installed.

Would it be too much trouble to request a config option to have this message suppressed if the pack dev does not want to include the Wiki mod by default?

**Comment by bdew** [comment]
Huh? Are i'm not using InGameWiki... are you sure this message is coming from AE2Stuff ?

**Comment by OrdinatorStouff** [comment]
There was a miscommunication about this issue and you're right it seems as though this chat message is coming from ExtraCells, not AE2Stuff. Also seems to have a config option for it already as well...

Thank you for your time.
