### ISSUE TITLE
[1.7.10] AE2 Stuff Crystal Growth Chamber

### ISSUE THREAD

**Issue by janagyjr** [bdew/ae2stuff#170]
AE2 Stuff 0.5.1.61
AE2 rv3-beta-6

Server log:
https://gist.github.com/janagyjr/fe9023a5d879127177ac01ee22febb13

confirmed in creative single-player

**Comment by bdew** [comment]
You have rv3 beta version of AE2, but AE2Stuff version is for rv2 release. Use this instead: https://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
