### ISSUE TITLE
Add export/supply bus that can target specific slots

### ISSUE THREAD

**Issue by bdew** [bdew/ae2stuff#18]
bdew/neiaddons#32

**Comment by chloeprince** [comment]
I really would love to see this get made! I need it for the IC2 Fluid Nuclear Reactor! 
It would be helpful in other mods like Railcraft - using it with Loaders and Unloaders. It would be nice to be able to place items in specific cart slots in rail-carts and retrieve items from specific carts too.

**Comment by Mrkeserian** [comment]
Agreed. It would also be insanely useful for building fully automated setups with Factorization ore processing.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
