### ISSUE TITLE
Dependency on unreleased bdlib?

### ISSUE THREAD

**Issue by planetguy32** [bdew/ae2stuff#19]
Using AE2 Stuff version 0.2.0.21, the latest version on CurseForge:

[07:07:03] [Client thread/ERROR] [FML/]: The mod ae2stuff (AE2 Stuff) requires mod versions [bdlib@[1.7.2.76,)] to be available

I've checked your Curse and CurseForge pages, bdew.net, and your BDLib Github releases, and I've been unable to find version 1.7.2.76. Is there anywhere else I should check?

**Comment by bdew** [comment]
Curseforge has [AE2 Stuff 0.2.1](http://minecraft.curseforge.com/mc-mods/225194-ae2-stuff/files/2236796) that is built against the right version of BDLib
