### ISSUE TITLE
Crystal Growth Chamber Disappear

### ISSUE THREAD

**Issue by Neodark7** [bdew/ae2stuff#2]
Hi nice mod but when i place the Crystal Growth Chamber on my network the block instantly disappear,
i can't give more infos about this :/

**Comment by bdew** [comment]
Hopefully fixed in eb090d495bbbde3e9ba28e9a8c7258ae186b9ead

**Comment by Neodark7** [comment]
http://jenkins.bdew.net/job/ae2stuff-1.7.10/7/ This i guess ?

**Comment by bdew** [comment]
Yes. Note that you will need the latest build of bdlib (1.6.0) from jenkins as well.

**Comment by Neodark7** [comment]
off course :)

**Comment by Neodark7** [comment]
of course :)
