### ISSUE TITLE
[Suggestion] Pattern storage for the advanced inscriber?

### ISSUE THREAD

**Issue by nitelite** [bdew/ae2stuff#24]
Maybe add 5 inventory slots on the left side of the advanced inscriber so that you can store your 5 different patterns there if you are doing manual crafting of your ME bits. That way you easily just take your gold ingot, redstone and silicon over to the machine, pick up the right pattern and make the bits.

Feels like something a real machine like this might have. If you don't want to change the machine too much from the beginning, you could even do it as a basic upgrade card that you slot in that activates those pattern storage slots.

Just a suggestion :) Feel free to close this when you see it.

**Comment by bdew** [comment]
The intention is to have separate machines for every process once you are past the very early game. I don't really see the value in this, sorry.
