### ISSUE TITLE
Feature Suggestion: Craftable Inscribers

### ISSUE THREAD

**Issue by Badcholo** [bdew/ae2stuff#25]
Craftable Inscribers press: maybe a single use craftable stone/iron inscriber press.
Craftable Skystone:
Or Skystone that spawns underground like ores.
I didn't like the craters So i removed them. All of them get found and none are left for players. That also removes skystone but it is used for crafting.

**Comment by bdew** [comment]
I don't think i'll add this to the main mod, but i'll provide a drop in config file with recipes for skystone and the inscriber plates.

**Comment by Badcholo** [comment]
Awsome!, Thank you..
