### ISSUE TITLE
Advanced Inscribers item extraction issue

### ISSUE THREAD

**Issue by MRuth** [bdew/ae2stuff#26]
Using the latest ae2stuff, it does not seem like Inscriber Presses are able to be extracted once inserted into the advanced inscribers.  Is this intended, and if so, could it be changed to allow extraction of the presses along with everything else?

Thanks.

**Comment by bdew** [comment]
I like how it works now because it allows automation without filters on everything. I'll think of a way to add this as an option while keeping the current behavior as the default.

**Comment by MRuth** [comment]
Maybe as a config option, or possibly a per machine option in the GUI?

**Comment by bdew** [comment]
I'm adding a gui button that locks/unlocks the top/bottom slot. Default is locked (which behaves like now). 

If unlocked AND the middle slot is empty  AND no current process is ongoing - the top/bottom slot will be able to be removed by automation.
