### ISSUE TITLE
Suggestion: Advance Crystal Charger.

### ISSUE THREAD

**Issue by KaneHart** [bdew/ae2stuff#28]
Since you have done most of your world in the basic tools to getting your AE System going then I wanted to suggest maybe a better method doing charge certus rather then the pain in the but machine we have now :)

Thanks

**Comment by Skar78** [comment]
+1 :)

**Comment by Mrkeserian** [comment]
The Crystal charger's sidedness isn't that bad. Fairly early automation is possible with hoppers and anything that can pull from the side of a block. But still, I'll third this.

**Comment by Karmacopper** [comment]
+1 for this :dancers:

**Comment by Skyler-Altol** [comment]
+1 for this, I was literally going to post the same thing xD

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
