### ISSUE TITLE
0.2.1.22 issues

### ISSUE THREAD

**Issue by xenoflot** [bdew/ae2stuff#29]
Hi, I've found the following issues:

1. Shift-right click doesn't break the growth chamber block.

2. Completed items are not auto-ejected. This means in addition to an interface, I also need an import bus, which I then need to filter.

3. Project overview states the ability to add 3 speed upgrades. The UI at the moment has only inventory slots, no upgrade slots.

Thanks for this mod! Makes life easier when I have a magnet on me. No more half grown seeds flying across the room!

**Comment by bdew** [comment]
> Shift-right click doesn't break the growth chamber block.

This is not implemented for now. Might add it in a future version.

> Completed items are not auto-ejected. 

Intended

> This means in addition to an interface, I also need an import bus, which I then need to filter.

You can use any other piping (or even a hopper) to put them back into the interface. No need for filtering, the block will only allow finished items to be pulled out

> Project overview states the ability to add 3 speed upgrades. The UI at the moment has only inventory slots, no upgrade slots.

Your version is too old. This was added in 0.3
