### ISSUE TITLE
inscriber recipes 

### ISSUE THREAD

**Issue by Staegrin** [bdew/ae2stuff#30]
![2015-06-01_19 14 38](https://cloud.githubusercontent.com/assets/8494635/7918554/7fddc6b4-0892-11e5-814d-f416c95a7b2d.png)
![2015-06-01_19 14 39](https://cloud.githubusercontent.com/assets/8494635/7918560/85de26f8-0892-11e5-89b9-c1caf248d76c.png)
![2015-06-01_19 14 41](https://cloud.githubusercontent.com/assets/8494635/7918563/89686cd4-0892-11e5-8078-d064efe8df13.png)
As the screen shots show the recipe is now the printed circuit at the top and printed silicon at the bottom. The center can now be any of those two or restone all three different items in the center will produce a processor. This error exists for all three processors.

**Comment by bdew** [comment]
That's... extremely odd.

Can you try removing AE2 Stuff and checking the recipes with plain AE2? Because i'm just grabbing them from AE2 API and not changing them in any way (also the NEI display in your screenshots is from AE2 itself as well).

**Comment by Staegrin** [comment]
Without AE stuff. Only the standard recipes are available.
![2015-06-01_21 01 30](https://cloud.githubusercontent.com/assets/8494635/7920779/78f9e774-08a1-11e5-8820-39899f46dc02.png)

**Comment by Staegrin** [comment]
Like you asked I turned off AE stuff and start the game.  Now I turned it back on and it seems to have fixed the problem. Will notify you if it starts again. 

It wasn't just an NEI problem I could make processors with two printed silicon and one printed circuit in the advanced inscriber.

**Comment by bdew** [comment]
I've looked through the code and i see no obvious reason why it could have happened.

Since it doesn't happen anymore i'll close this issue. If it comes back comment here or open a new one.
