### ISSUE TITLE
[Minor Bug] Move Pattern Encoder 'Encode' button

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#32]
Pattern Encoder 'Encode' button is at the same place on screen as NEI '?' button, which sometimes results in unwanted encoding when a player presses Shift+'?'.

![ae2-stuff](https://cloud.githubusercontent.com/assets/11259935/8035080/3fe43ce6-0df6-11e5-8873-dc91641698db.jpg)

**Comment by bdew** [comment]
Don't press the button twice? :P 

I don't see any better way to arrange that UI, moving them to the left looks weird.

**Comment by FREEZEball** [comment]
It's not pressing button twice. If your mouse button isn't released when the Encoder screen pops up, you instantly pick up a pattern. It only happens with shift-click though, like you are able to move items between inventory and chest - just hold the 'Shift' and mouse buttons then simply move your cursor above items. Yet it is annoying you need to watch where you are clicking (down half of '?' button). Maybe move it up just slightly, decreasing that arrow size?

**Comment by bdew** [comment]
It might be mouse tweaks. I tried with Inventory Tweaks and don't see that behavior - the pattern is taken out on mouse down normally, not up.

I'll play with how the gui is layed out when i have the time, but you should report it to Mouse Tweaks author.

**Comment by FREEZEball** [comment]
Thank you. I just wrote to the author of Mouse Tweaks, hope he responses aswell.

**Comment by bdew** [comment]
I've tried and can't find a setup that i'd like where that slot will not intersect the ? button in NEI.

Hopefully Mouse Tweaks dev(s) will be able to fix this on their sides.
