### ISSUE TITLE
[Feature Request] Encoding Patterns multiple times.

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#33]
AE2 Pattern Terminal can re-encode Patterns multiple times. Would be usable to have Pattern Encoder do this as well. Maybe placing encoded Pattern to the output slot would replace it's content. Or placing Pattern to the input slot to rewrite it manually.

**Comment by bdew** [comment]
You can wipe them with shift-clicking for now. I'll look into adding that.
