### ISSUE TITLE
ae2stuff's pattern encoder problem

### ISSUE THREAD

**Issue by oks1998** [bdew/ae2stuff#34]
when encode an blank pattern with the ae2stuff encoder and put it into the ae2 and autocraft it, it show crafting tree construction fail something like that, if use original ae2 encoder, it will work fine...i use ae2stuff's encoder to encode the ic2 crafting pattern and it show this problem.....the previous pattern that i encode with this mod still work as fine....

**Comment by bdew** [comment]
What item are you trying to craft and what versions of all mods involved?

Also there should be a more detailed error in your forge log, please provide that.

**Comment by oks1998** [comment]
i try to craft solar distiller in ic2 and my ic2 is industrialcraft-2-2.2.736-experimental
ae2stuff is ae2stuff-0.3.2.36-mc1.7.10
.....no error report..but error message in the game:

Error: java.util.concurrent.ExecutionException:
java.lang.RuntimeException: java.lang.RuntimeException:
Crafting Tree construction failed.

**Comment by bdew** [comment]
Please try this build: http://jenkins.bdew.net/job/ae2stuff-1.7.10/37/artifact/build/libs/ae2stuff-0.4.0.37-mc1.7.10.jar

Note that any currently-bugged patterns will stay bugged and you will need to replace the manually. This fix only affects new patterns encoding.

**Comment by oks1998** [comment]
ok thanks i will try :+1:  :)

**Comment by oks1998** [comment]
ya, it works fine~ thank you~ :)
