### ISSUE TITLE
Dupe bug in a patteren encoding

### ISSUE THREAD

**Issue by bsaksida** [bdew/ae2stuff#40]
When you place item in a patteren, it takes item and imidealty you get a refund. When at the same item is in your inventory. After you double click item in a inventory you will also grab items from crafting grid. To perform this dupe you need at minimu 2 items. And at max you can dupe 9 items.

also i noticed, you can place item in a preview slot, you lose that item. You can not get back

**Comment by bdew** [comment]
Try this build i think it should be fixed - http://jenkins.bdew.net/job/ae2stuff-1.7.10/42/artifact/build/libs/ae2stuff-0.4.2.42-mc1.7.10.jar

**Comment by bsaksida** [comment]
Its fixed. I can no longer dupe items
