### ISSUE TITLE
Crafting Terminal and Advanced Inscriber

### ISSUE THREAD

**Issue by mercsniper** [bdew/ae2stuff#43]
I created a pattern of:
Silicon Press            Silicon circuit
Silicon Ball                 

The Advanced Inscriber did not eject the circuit and I can't figure out how to pull the press back in through the crafting terminal. Any ideas?

**Comment by bdew** [comment]
It doesn't auto eject, you need to pull it out (with any kind of piping or an import bus) just like you do from other machines and the normal inscriber.
