### ISSUE TITLE
[Enhancement] Allow the pattern encoder to be crafted into a multipart, take on color of connecting cable

### ISSUE THREAD

**Issue by utoc** [bdew/ae2stuff#44]
If it wouldn't be a bother, it would be nice if the pattern encoder could be crafted into a multipart by placing itself in a crafting window, much like the ME Interface does now.  This way, it could be attached directly to a fluix/covered cable with a facade placed in the same block space for a more asthetically pleasing presentation.  Additionally, if it isn't too much more bother, it would be great if the pattern encoder picked up its color from the cable it was attached to in the same way that Crafting terminals take on the color of the cable connecting them.

Let me know if my explanation has fallen short of your expectation.

**Comment by bdew** [comment]
Multiparts are planned, but it's pretty complicated so it may take a while until i get there.

I'll add the color thing.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
