### ISSUE TITLE
[Bug] Crash on Wooden Chest pattern encode.

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#46]
Crashes when I try to encode a pattern with the recipe of the Wooden Chest. Pack - Resonant Rise 3 (183 mods), single player world, recipe taken from NEI (shift+clicking on '?' symbol). I suppose, it tries to encode all types of wooden planks from the Forge Ore Dictionary?

Encoding the same recipe with AE2 Pattern Terminal doesn't trigger an exception.

![Error](http://i.imgur.com/GeHektr.png)
[Full log (ATLauncher log hosting)](http://paste.atlauncher.com/view/06f8ab36), time is [15/7/2015 12:55:54 PM]

Minecraft 1.7.10
Applied Energistics rv2 stable 10
AE2Stuff 0.4.0.38

**Comment by bdew** [comment]
Just how many wood types that pack have? 0.o

Try this build: http://jenkins.bdew.net/job/ae2stuff-1.7.10/45/artifact/build/libs/ae2stuff-0.4.3.45-mc1.7.10.jar

I've made the packet to set patterns somewhat smaller, hopefully it will be enough to fit in that 32k limit.

**Comment by FREEZEball** [comment]
The issue doesn't occur anymore. I went even further, and tested it with 258 mod pack - it is working.
