### ISSUE TITLE
Render crash upon adding this mod

### ISSUE THREAD

**Issue by Serifina** [bdew/ae2stuff#51]
Not sure why, but as soon as I added this mod, Minecraft decided working was too good for me. Related crashlog here: http://pastebin.com/fDWCFk5C

As far as I can tell, it's AE2Stuff, which is strange considering how a) I haven't even started AE yet, b) I was in the Twilight Forest and my base is in the overworld, but the only mod referenced is ae2Stuff and adding this mod (and the dependency) was literally the only thing changed when I went from stable to crash.

**Comment by bdew** [comment]
Please try this build and report if it fixes the crash (or not) - http://jenkins.bdew.net/job/ae2stuff-1.7.10/50/artifact/build/libs/ae2stuff-0.5.0.50-mc1.7.10.jar

**Comment by Serifina** [comment]
Gave it a try - near as I can tell, that's fixed it. Played around in-game for ten minutes, checked the same areas I was in before, mobs, etc, no crashes occurred.
