### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by cauliflower69** [bdew/ae2stuff#52]
http://pastebin.com/jASeXExn

We are running our server on KCauldron and after updating a group of mods people were getting a fatal error and being disconnected from the server with the following crash http://pastebin.com/rdSeAjwU

I then decided to move the server back over to Forge to troubleshoot and then the above crash happens. Odd that it boots fine on Cauldron but not with Forge. 

I updated both bdlib and ae2stuff and still the same crash. I managed to get the server working again by downgrading ae2stuff and bdlib and using Cauldron again.

**Comment by bdew** [comment]
> http://pastebin.com/jASeXExn
> Caused by: java.lang.ClassNotFoundException: scala.util.parsing.combinator.JavaTokenParsers

This is a bad install, you are missing a library that should have been installed by forge installer.

> http://pastebin.com/rdSeAjwU
> There was a critical exception handling a packet on channel XU|Pkt

Looks like a bug in Extra Utilities (or possibly kcauldron?). No mentions of my code in this log at all.

**Comment by cauliflower69** [comment]
Thanks for the reply.

**Comment by bdew** [comment]
Forgot to mention it in my previous reply, the missing file in the first crash is

libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
