### ISSUE TITLE
[Feature Request] An advanced Memory Card (?)

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#53]
There are no way to tell which [P2P Tunnel](http://ae-mod.info/P2P-Tunnel/) is connected to what. I'd suggest an upgraded version of a [Memory Card](http://ae-mod.info/Memory-Card/) which has an option of showing player where previously selected P2P tunnel is connected to. Maybe a GUI line across the world, or highlight paired tunnels, or simply output paired tunnel's coordinates in chat (although it isn't very informative, because u can stack up to 5 tunnels around a cable inside a single Minecraft block). Number of tunneled channels might also be very helpful.

Thanks, and sorry once again about my poor English :)

**Comment by bdew** [comment]
I'm currently working on a visualisation tool that can show something like this:

![2015-08-06_16 35 05](https://cloud.githubusercontent.com/assets/96327/9112762/5c9f69a0-3c59-11e5-94ac-df76c146e93e.png)

Note that it shows all network connections, but also what tunnels are going where.

Would that cover your use case?

**Comment by FREEZEball** [comment]
This is awesome!

Although, maybe add a color differentiation between channels and tunnels? Or even better add switchable modes (Channels/Tunnels/Everything) to the tool? My point is full visualization might be not very informative with big networks.

**Comment by bdew** [comment]
![2015-08-11_12 05 13](https://cloud.githubusercontent.com/assets/96327/9194176/0daf7b7e-4022-11e5-9f73-93041e415674.png)

How about that? The visualisation is still WIP but should be more useful now i think.

Also this is now in the alpha versions starting with build 52.

**Comment by FREEZEball** [comment]
Yeah, this is great as is. One last suggestion: make it an upgradeable version of [Network Tool](http://ae-mod.info/Network-Tool/). It would be really versatile and powerful tool.

**Comment by bdew** [comment]
I really don't want to mess with the Network Tool. The way it's inventory is being shown in AE machines is pretty complicated and would require some hackery to work with anything else.

What features would you find usefull as upgrades? I might implement some in a separate tool.

**Comment by FREEZEball** [comment]
It is fine then. I think I have some more ideas, but I will create new threads when I think them over.
