### ISSUE TITLE
Advanced Inscriber eating power

### ISSUE THREAD

**Issue by BeyJohn** [bdew/ae2stuff#56]
I put down the advanced inscriber and wire it up to my already existing system and all the power in my system gets pulled and the inscriber doesn't gain any power and doesn't do any work.

**Comment by BeyJohn** [comment]
It seems that the energy cell I had on the network was sucking up all the power generation. Maybe you should consider giving your machines a bit of priority when it comes to power, or allowing them to draw from energy cells on the network. Also when you break the inscriber while there is work going on you lose the item/items it consumed to begin the process.

**Comment by bdew** [comment]
They can draw from cells but will only do it if the charge is above 20% to prevent brownouts or things going on/off constantly (which is bad for performance).

Did that happen with the latest version?

**Comment by BeyJohn** [comment]
Yes it did, and that makes sense, but there is still the issue of breaking the inscriber mid-process adn losing any items it had eaten to begin the process.

**Comment by bdew** [comment]
It should keep inventory and energy when broken, but it's not implemented yet :P

**Comment by BeyJohn** [comment]
Ahh ok, thank you for clearing that up for me.
