### ISSUE TITLE
Crash when placing Network Extender

### ISSUE THREAD

**Issue by KidMessiah** [bdew/ae2stuff#58]
http://pastebin.com/yHjqdvch
So when I place the block, I crash entirely, I can relaunch and play fine, everything works fine. But everytime I place one, it crashes the game.

**Comment by bdew** [comment]
AE2 rv3 alpha is not supported by the main builds of AE2 Stuff.

If you play rv3 alpha you need the [builds tagged with -rv3](http://minecraft.curseforge.com/mc-mods/225194-ae2-stuff/files) (currently the most recent one is ae2stuff-rv3-0.5.0.1-mc1.7.10.jar)

Note that they might be behind in features for a while. If you want to test the most recent stuff in AE Stuff - you will need AE2 rv2.
