### ISSUE TITLE
[Bug] Can't place AE2Stuff Blocks aftr updating to 0.5.0.52

### ISSUE THREAD

**Issue by p455w0rd** [bdew/ae2stuff#59]
Updated bdlib to 1.9.2.102 as well, Running AE2 RV3 Alpha 3, When I place any AE2Stuff blocks, they disappear. Also, the inscribers I already had placed disappeared. Pastebin of relevant info: http://pastebin.com/6aezXv2F

**Comment by bdew** [comment]
The normal builds of AE2 stuff do not support AE2 rv3 Alpha.

Use the builds here instead - http://jenkins.bdew.net/job/ae2stuff-1.7.10-rv3/

**Comment by p455w0rd** [comment]
Sorry about that..I was actually just testing that version after browsing jenkins. Thanks for the prompt response!
