### ISSUE TITLE
Compatibility to rv2

### ISSUE THREAD

**Issue by BakermanLP** [bdew/ae2stuff#6]
Hello,
I only wanted to ask you, if you can make this mod compatible to applied energistcs rv2. The beta version is out now.
Thanks!
Michael (aka BakermanLP)

**Comment by bdew** [comment]
http://jenkins.bdew.net/job/ae2stuff-1.7.10/

0.1.1 is for AE rv2-beta and BDLib 1.5.1 (current stable)
0.1.2 is for AE rv2-beta and BDLib 1.6.0 (dev builds)
