### ISSUE TITLE
Crashes with Latest AE2 RV3

### ISSUE THREAD

**Issue by chloeprince** [bdew/ae2stuff#61]
Hey BDew,

I tried using ae2stuff-0.5.0.52-mc1.7.10.jar with appliedenergistics2-rv3-alpha-4.jar and I get this crash:

http://pastebin.com/XzmHCLyb

Can you update to the latest version of AE2 :)

**Comment by bdew** [comment]
The normal builds of AE2 Stuff do not support AE2 rv3 Alpha, they are meant for rv2 Stable.

Use the builds here instead - http://jenkins.bdew.net/job/ae2stuff-1.7.10-rv3/

Note that you will probably need the latest alpha of bdlib and possibly my other mods.
