### ISSUE TITLE
[Feature Request] Pattern Encoder - allowing multiple output production Patterns + NEI enchancment

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#62]
That would be great to use Pattern Encoder similar way to AE1 not only for crafting Patterns, but also for production ones. Maybe through the toggle-able button, like in ME Pattern Terminal.

More to that, is it possible to have '?'-button for production recipes in NEI while inside Pattern Encoder's GUI? At least for popular actions - pulverizing, smelting etc. Most painful action while encoding tons of Patterns is to race between ME Pattern Terminal, Pattern Encoder and machines to make bits and blobs of everything.

Sorry about my poor English.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
