### ISSUE TITLE
[Enchancment] Pattern Encoder checking network for oredictionary components.

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#63]
Pattern Encoder is always connected to the system, but only receives power from it. Also, it does often create recipes which are not properly working with oredictionary *(I honestly don't know the reason, but it does it very often - for example, if recipe needs Hardened Glass from TE or Quartz Glass from EnderIO, it always writes Quartz Glass on the Pattern, refuses to craft from Hardened Glass at all, untill I correct it manually; what is going on with ingots from different mods, is even worse)*, so my suggestion is to have it check connected network for the most amount of  written to recipe components.

I think it is a bad idea, but worth trying.

Sorry about my poor English.

**Comment by bdew** [comment]
It already does that, it takes the first variant of an item that is stored or craftable in the network (if there is one)
