### ISSUE TITLE
[Feature Request] Advanced Molecular Assemblers

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#64]
That would be good to have Advanced Molecular Assemblers which have an inventory for 5+ crafts and maybe more slots for Acceleration Cards. Issue with AE2 ones is you have that massive space consuming 'flowers'  which are needed for some recipes. So my suggestion is to make 5 *(I always connect 5 to every ME Interface, some may be used for more ME Interfaces - depending on how much free space do I have)* of them into one, maybe with only one 'interface' side - to make sure people won't connect more than one ME Interface to them.

Also another small problem is Assemblers are showing crafted item inside the block. It is unnecessary, and may require some rendering power. Possible solution - make opaque and non-opaque versions?

Sorry about my poor English.

**Comment by bdew** [comment]
I like the current system in AE, it's versatile - you can do flowers, you can put them in grid patterns, etc. depending on your needs and available space and resources.

I don't think this is something that needs changing.
