### ISSUE TITLE
[Feature Request] Network Terminal + Channel Switch/Switch Cable

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#65]
Another suggestion is a Channel Switch block or Switch Cable, that might be placed instead of one piece of ME Cable, transferring it's channels as normal Cable would, but have a GUI where you can name this specific Switch and one card slot for Redstone Card which allows you to control the Switch via Redstone. Switch is needed to enable and disable channels coming through it.

So you also have an ME Network Terminal, which works as a stationary [Network Tool](http://ae-mod.info/Network-Tool/) but also has an ability to remotely control all Switches inside this network, manually switching on and off channels coming through it.

To balance things a bit, Channel Switch blocks themselves might need a channel to work.

Also very nice feature would be an automatic enabling/disabling all checked for it Switches. Maybe with Redstone Card inside the slot of Network Terminal and Redstone signal coming into it. This gives a possibility to disable all ME Wireless Transmitters, if power is too low, for example.

Sorry about my poor English.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
