### ISSUE TITLE
Power Crystal Growth Chamber from ME Interface

### ISSUE THREAD

**Issue by p455w0rd** [bdew/ae2stuff#67]
What the title says..this is the general functionality with AE2 blocks..I thought my growth chamber was bugged till I saw it had no power in WAILA. Also, perhaps crescent hammer support?

**Comment by bdew** [comment]
It should be able to draw power through interfaces. What's your exact setup?

Do you have enough power? It will stop drawing power if your network is below 20% total power storage to prevent brownouts or things going on/off constantly (which is bad for performance).

Also interfaces don't transmit power or channels on the side they are pointing to (with the arrow). 

Disassembling with wrenches, crescent hammers, etc. is on my todo list (already requested in #55)

**Comment by p455w0rd** [comment]
AE system is drawing power via tesseract from tier 7 draconic storage multiblock with 700+ billion RF. It is a flat interface..dunno if that makes a difference, but the adv inscribers seem to be doing fine with the same setup. Running AE2 RV3 A5 w/AE2Stuff RV3..the interface is on the bottom..I would provide a screenshot but's buried far back in a corner..

**Comment by bdew** [comment]
Yeah the multipart (flat) interfaces don't transfer power to machines they are connected to either. You'll need to provide power from one of the other faces.
