### ISSUE TITLE
[Suggestion] rf support?

### ISSUE THREAD

**Issue by p455w0rd** [bdew/ae2stuff#68]
AE2 has the option in the configs to work via RF without the need for an energy acceptor. This is how I run AE2 on my server. It allows me to power things using TE ducts or EnderIO conduits. This is really handy when using EnderIO since it supports multiple conduits in the same block. I figured since it's supported by AE2, it probably should be implemented in subsequent addons.

**Comment by bdew** [comment]
I do plan to add support for other power systems in the future after fixing some existing issues i have with how machines handle energy.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
