### ISSUE TITLE
Add option to change displayed power unit

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#69]
WAILA's UI shows WIreless Connector's power in AE by default and there is no config file for AE2 Stuff (?). I suggest to make WAILA show power in configurable unit. One way to take it is from 

```
\config\AppliedEnergistics2\AppliedEnergistics2.cfg

S:PowerUnit=AE // AE, EU, WA, RF, MK
```

Sorry about my poor English.

Edit: fixed.

**Comment by bdew** [comment]
My WAILA handler is showing power use in AE. If you see EU in WAILA then it's some other mod doing something weird.

I do plan to add support for different power unit display in the future.

**Comment by FREEZEball** [comment]
I meant AE, sorry.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
