### ISSUE TITLE
[Feature Request] Network Visualisation Tool => 'Priority' mode

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#71]
Maybe it is just me, but I love to change priorities on every component, and today I actually ran into situation where I needed to find why one of my Alloy Smelters didn't work. So it might be not really useful and definitely not a , but I'd still suggest to add the mode which shows priorities of network components.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
