### ISSUE TITLE
Crash after update: java.lang.NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/Collection;

### ISSUE THREAD

**Issue by BBoldt** [bdew/ae2stuff#73]
https://www.dropbox.com/s/oouzoauzvk5m3jl/crash-2015-09-20_02.42.40-server.txt?dl=0

I may have paired up the wrong versions of mods or something, not quite sure.

* forge-1.7.10-10.13.4.1492
* bdlib-1.9.2.104-mc1.7.10
* ae2stuff-rv3-0.5.0.4-mc1.7.10
* appliedenergistics2-rv2-stable-10

Sorry if this is a dumb mistake or something like that.

**Comment by bdew** [comment]
ae2stuff-**rv3**-0.5.0.4-mc1.7.10
appliedenergistics2-**rv2**-stable-10

Note the bold parts :P

You need normal AE2 Stuff (without rv3 in the file name) for AE2 rv2

**Comment by BBoldt** [comment]
oops
