### ISSUE TITLE
SMP Crash (NoClassDefFoundError)

### ISSUE THREAD

**Issue by jburrows82** [bdew/ae2stuff#74]
http://pastebin.com/gvLWY5Jq

I was placing a Wireless Connector down on a Ztones block in creative mode.

**Comment by jburrows82** [comment]
My apologies -- I'm using the RV3 version of AE2stuff on RV2 stable. Sorry for opening this issue!

**Comment by Dream-Master** [comment]
I ran in the same issue before didn't read that it is for rv3.
