### ISSUE TITLE
[Suggestion] Add AutoExport card for AE2stuff machines

### ISSUE THREAD

**Issue by bsaksida** [bdew/ae2stuff#77]
On my previous computer i could kill fps on minecraft with fully upgraded import busses. After experimenting i could easly put interface close to machine, and then machine auto-eject into interface. This was a big tick wise improvments.

I suggest adding upgrade cart that enables to auto eject to either block with inventory or directly into ae.

**Comment by bdew** [comment]
I'll consider this.

Do note that you use any kind of piping from other mods to pipe items out and put them in an interface, avoiding the need for an import bus one each machine.

**Comment by NightOps007** [comment]
Perhaps, instead of autoexport, could add a sneaky insertion card. Shift right click it on the side of a block that you want items to be inserted on the connected machine, put it in the interface and shazam. You can have your interface at the output and sneak items into where ever the input is.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
