### ISSUE TITLE
[Feature Request] Robotic Tape Silo

### ISSUE THREAD

**Issue by mskurnik** [bdew/ae2stuff#78]
There is an older piece of tech that would be ideal for AE2Stuff...A Robotic Tape Silo.  A problem that many of us come across is that in order to have capacity for all of the different patters we want on the network, we have to add more interfaces and more assemblers as time goes on.  I thought it would be great to have a structure that you could build that would drastically reduce the amount of assemblers and interfaces you need. The silo would be a multi block structure of a configurable size that would let you place your patterns for the molecular assembler (and maybe eventually other machines) into to it and then have it act as an interface to attached molecular assemblers.  You can watch a video of a silo here https://www.youtube.com/watch?v=Ll1gaeM1ukY from YouTube.

Essentially the structure would load the patterns you needed when you go to make something.  I am not sure if a structure like this is even possible.  Feel free to hit me up with more info or to bounce ideas off of.

Thanks!

**Comment by bdew** [comment]
Sounds kinda like how the old MAC was in AE1, except only for pattern storage with the actual assemblers outside it?

To be honest i like it how it's right now with interfaces/assemblers - it gives some space for creativity where different setups can be made depending on player needs.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
