### ISSUE TITLE
Inscriber/Growth GUI don't fetch overlay icons for slots

### ISSUE THREAD

**Issue by HanFox** [bdew/ae2stuff#79]
Here's the AE2 Inscriber:
http://puu.sh/kId6s/6651022974.png

vs the AE2Stuff Inscriber:
http://puu.sh/kId8J/f91cba8cbb.png

(It's not a resourcepack error before you notice the non-default textures, that's just the base pack changed in those screenshots ;))

The Crystal Growth Chamber is also missing the upgrade slot overlays.

**Comment by bdew** [comment]
Yeah not implemented yet, i'll add it in a future version.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
