### ISSUE TITLE
[Feature Request] Add-on for recipe storage and sorting

### ISSUE THREAD

**Issue by adamvan2000** [bdew/ae2stuff#80]
I would like to suggest a block for storing recipes for access by assemblers on the same network as the block. It'd be awesome if it could also sort said recipes. I currently have 12 assemblers with 6 interfaces per assembler and 9 slots per interface, that's 648 recipes. That's a lot to load, sort, etc...

**Comment by bdew** [comment]
Seems to be similar to the suggestion in #78.

I'm not sure if it's even possible to provide recipes for assemblers from remote blocks, and i'm not decided on whether i want to implement something like that at all.

As i said in the other suggestion - i like how the current interface/assembler mechanic works and wouldn't want to undermine it.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
