### ISSUE TITLE
[Feature request] Advanced Interface

### ISSUE THREAD

**Issue by artubi** [bdew/ae2stuff#81]
Hi,
I would like to request an "Advanced ME Interface". Basically, ME Interface with increased storage for patterns. Instead of 1 row (9 slots) it would have 3 to 5 rows (27 to 45 slots).
Reason behind that is quite simple, to reduce the number of interfaces needed in order to automate crafting and therefore reducing load on the game.

I personally had issue that in order to automate most used items, I had to use about 46 interfaces. Alongside with the machines used within AE autocrafting, it caused a quite lot stuttering. Especially in / near the chunks containing AE.

**Comment by NightOps007** [comment]
Oooh, yes please. You could make have it 2 rows by default and expandable with capacity cards. Perhaps the input slots should increase as well so you can use it to auto-stockpile certain items by using a storage bus and crafting card with it.

**Comment by eldblz** [comment]
Good idea maybe advanced interface should require 2 channels to work just to balance things out.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
