### ISSUE TITLE
[Feature Request] Network Visualisation Tool => Tunnels across dimensions

### ISSUE THREAD

**Issue by Belgabor** [bdew/ae2stuff#83]
I love the visualization tool, there is only one feature I'm missing, being able to track p2p tunnels across dimensions. I have two suggestions that would complement each other:
- When hovering over a tunnel that crosses dimensions (or even goes very far in the same one) show target dimension and coordinates
- Select a specific tunnel with the tool, opposite part gets highlighted once you approach it

**Comment by fchtngr** [comment]
Selecting a specific tunnel would also be very useful in the same dimension. Once you have a lot of p2p tunnels the visualization doesn't really help anymore.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
