### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by chloeprince** [bdew/ae2stuff#84]
Hey Bdew,

My server is crashing because someone placed the AE2 Stuff Inscriber into the world. Now My server keeps crashing when it tries to reboot.

https://gist.github.com/chloeprince/b909f0c12b1889cb86a4

**Comment by bdew** [comment]
AE2 rv3 alpha has backwards incompatible changes, you need to use build of AE2 Stuff from -rv3 branch with it. The last one is here: http://minecraft.curseforge.com/projects/ae2-stuff/files/2257655
