### ISSUE TITLE
AE2stuff blocks get duplicated in the AE network on chunk unload/reload

### ISSUE THREAD

**Issue by ab9rf** [bdew/ae2stuff#86]
I've had a world now (Forge 1517, AE rv2-stable-10, AE2stuff 0.5.0.56, bdlib 1.9.2.104, although also happened with 0.4.3.47/1.9.1.97 version of AE2stuff and bdlib) with a network containing one each of a crystal growth chamber, a pattern encoder, and an AE2 advanced inscriber. Over time, the number of these blocks, as reported by an AE2 network tool, steadily grows; since the pattern encoder draws power continuously this causes the power drain to grow, essentially without bound. 208 pattern encoders draw a lot of power.

I've determined that this happens when the chunks containing the network are unloaded and reloaded; I can cause the counts to increment by one by disconnecting and reconnecting, which (of course) causes a chunk unload/reload. My best guess is that the pattern encoder is not removed from the network on chunk unload, but is readded to it on chunk load, leading to multiple instances in the network.

Breaking the block containing the pattern encoder removes only one instance from the network, leaving any phantoms behind. (Doesn't matter whether I use a pickaxe or a wrench.) The ME cable connecting the encoder to the network remains, apparently connecting to nothing. Breaking that cable removes all of the phantom encoders and resolves the power drain issue. The same thing happens with the phantom advanced inscribers and crystal growth chambers, but as these don't draw passive power they're less of a concern.

Obviously, I could obviate this by using chunkloaders, and that's likely what I'll do as a workaround, but I thought I'd report it.

**Comment by bdew** [comment]
That's odd, i think i know what's going on, but i can't reproduce it.

Does some part of the network remain chunk loaded while the area is unloaded?

**Comment by bdew** [comment]
At any rate, please try this build: http://jenkins.bdew.net/job/ae2stuff-1.7.10/60/artifact/build/libs/ae2stuff-0.5.1.60-mc1.7.10.jar

I think it will fix this issue.

You might need to update BDLib as well to a newer build: http://jenkins.bdew.net/job/bdlib-1.7.10/109/artifact/build/libs/bdlib-1.9.4.109-mc1.7.10.jar

**Comment by ab9rf** [comment]
It's possible (indeed likely) that part of the network is in the server spawn protection area and thus remains loaded even when all players are disconnected.

I am not observing the problem with the builds recommended above (tested both by disconnecting and reconnecting, and by moving away so that the chunks unload while still connected). Thanks for the quick attention to this issue.
