### ISSUE TITLE
Not open-source

### ISSUE THREAD

**Issue by joepie91** [bdew/ae2stuff#88]
The [Curse page](http://www.curse.com/mc-mods/minecraft/225194-ae2-stuff) states that this mod is open-source - however, the [MMPL-1.0 license](http://bdew.net/minecraft-mod-public-license/) that is used does not meet the [Open Source Definition](http://opensource.org/osd-annotated), and thus _cannot_ be called "open-source".

Specifically, the following point is violated by the MMPL's requirement to own a legally acquired Minecraft license:

> 7) [...] The rights attached to the program must apply to all to whom the program is redistributed without the need for execution of an additional license by those parties.

Possible other violations are point 8 (due to the exemption for Minecraft and modloader code) and point 9 (due to the requirement that all "dependencies" are licensed "under comparable conditions" - neither of those terms is well-defined).

Aside from the above issues, I'd generally not recommend using this license - it is extremely poorly and/or vaguely worded in some sections, full of grammar issues, and I strongly doubt that this license has received any legal review whatsoever; this means that it may very well be completely invalid.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
