### ISSUE TITLE
Error in log file

### ISSUE THREAD

**Issue by Tsyklop** [bdew/ae2stuff#89]
http://pastebin.com/EeCJEUB3

AE2 rv3 alpha13, ae2stuff-rv3-0.5.1.9-mc1.7.10

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2009

**Comment by bdew** [comment]
Unless i'm missing something this error has nothing to do with my mod, it's between AE2 itself and Extra Utilities.
