### ISSUE TITLE
Crash to desktop when opening the Crystal Growth Chamber or the Pattern Encoder

### ISSUE THREAD

**Issue by Staegrin** [bdew/ae2stuff#9]
Just read your post over at your minecraft forum page for advanced generators. Hope you get well soon. Real life comes first.

This started happening after updating to bdlib-mc1710-1.6.0.36
When opening the Crystal Growth Chamber or the Pattern Encoder I crash to desktop.
The Crystal Growth Chamber does still work without issues. Just can't open the UI.

crash log:
http://pastebin.com/YYXKMeLT

**Comment by abdullamu** [comment]
here is the same crash when open ui

http://pastebin.com/webqqGfd

**Comment by bdew** [comment]
Those crashes are really odd. It's in vanilla code and unless i'm missing something it would mean that Minecraft.thePlayer is null (which would break everything else). It could be some coremod messing something up too.

Can you reproduce it with just AE, AE2Stuff, bdlib, CCC and NEI?

**Comment by Staegrin** [comment]
with only those 5 mods/libraries it still crashes to desktop when opening either the Crystal Growth Chamber or the Pattern Encoder.
crash log:
http://pastebin.com/QJwsLRZu

**Comment by bdew** [comment]
Please try this version: http://jenkins.bdew.net/job/ae2stuff-1.7.10/7/artifact/build/libs/ae2stuff-mc1710-0.1.2.7.jar 

I didn't notice that you used an older version when looking at it for the first time. Still no idea why it crashes like that, but i think the newer build will work correctly.

**Comment by Staegrin** [comment]
Everything works without crash. Also no conflicts/crashes after adding more mods to it.

Hope you're getting better after being sick.
