### ISSUE TITLE
Placing Advanced Inscriber Crash

### ISSUE THREAD

**Issue by BenB196** [bdew/ae2stuff#92]
Every time I place an advanced inscriber my game crashes and i have to delete the block using mcedit to get back in.

attached in pastebin link is the crash report.

http://pastebin.com/HEqbZBLE

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
