### ISSUE TITLE
[Bug] Advanced Incriber causing AE Crafting CO-Proc and Storage blocks to break

### ISSUE THREAD

**Issue by mindcloud69** [bdew/ae2stuff#96]
I have been following [this setup from reddit](https://www.reddit.com/r/feedthebeast/comments/34ffwk/i_updated_my_5x5x5_controller_now_with_wireless/) and I replaced the inscribers in the tutorial with advanced inscribers. When I place the crafting storage and processors from level 2 of the tutorial they spontaneously break like you used a pickaxe on them when placed over the inscribers. It doesn't happen the same way every time sometimes they will stay and then I will place another block above it on level 3 and the level 2 blocks break again. This doesn't happen when you use regular AE2 inscribers. This occurs in both single player and MP.

![2016-01-19_23 15 13](https://cloud.githubusercontent.com/assets/3201188/12439786/ca2ab84a-bf02-11e5-850a-bfb158f349aa.png)

Using a modified FTB Infinity Evolved: Normal mode.
Forge 1566
AE2 Rev 3 Beta 5
AE2 Stuff rev3-0.5.1.9
[Client log.](https://gist.github.com/mindcloud69/0740a069addf5b85662f) 
Note: I have Optifine installed the error occurred with and without it installed.

**Comment by bdew** [comment]
I noticed that the tutorial mentions a security terminal, do you have it already placed?

Might be related to #95

**Comment by mindcloud69** [comment]
It happened with and without the security station including with and without a bio-metric card installed. Also happened with and without power. It also didn't seam to matter which crafting block is was either. If you can think of any other combos you want me to try let me know. Additionally I was able to move the adv inscribers down a level so they were only connected by flux cable and item conduits as a test, so they were not touching any of the crafting blocks and there were not any problems with that setup.

**Comment by mindcloud69** [comment]
Any word on fixing this bug?

**Comment by bdew** [comment]
I couldn't reproduce it and have no idea why it would happen, and currently mostly working on 1.9 stuff.

**Comment by mindcloud69** [comment]
Ok thanks for the response I'll just close this for now then. Thank you for your hard work as well!
