### ISSUE TITLE
AE2 Stuff block crashes server

### ISSUE THREAD

**Issue by Dream-Master** [bdew/ae2stuff#97]
We have a crash today on the Server when placing a Wireless connector.

Server crash log:
https://github.com/bdew/ae2stuff/issues/95

Mods used in a Modpack
ae2stuff-0.5.1.61-mc1.7.10
appliedenergistics2-rv3-beta-4

Modpack:
https://github.com/GTNewHorizons/NewHorizons

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

**Comment by Dream-Master** [comment]
ok thanks
