### ISSUE TITLE
[Feature Request] Quantum Terminal

### ISSUE THREAD

**Issue by NightOps007** [bdew/ae2stuff#98]
### **Main idea:**

Add wireless terminal with no range/dimension restrictions. Shift+right click opens GUI to add your quantum entangled singularity and needs its counterpart in a on-line quantum bridge multiblock to connect your terminal to the network. Normal right click opens terminal to access items in the network. Power is only consumed when the terminal is open(quantum bridge established only when in use). Maybe it should draw its power needs directly from the network like any good quantum bridge. 
### **Possible branches:**

Perhaps you should have to add the terminal of your choice in the same GUI you add the singularity(crafting terminal maybe). Or perhaps it is not a quantum terminal, but a quantum crafting terminal.
Perhaps you craft it with all four terminals and by shift+mousewheel, you can switch between them.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
