### ISSUE TITLE
[Major Crash] Crashing (Out of date API?)

### ISSUE THREAD

**Issue by StoneLegion** [bdew/ae2stuff#99]
Having this the second I placed the Advance Inscriber. It's in a loop crash now:
http://pastebin.com/TRzgWrMF

**Comment by bdew** [comment]
If you are using AE2 rv3 alpha/beta you need the -rv3 builds of AE2 Stuff.

http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
